server {
    listen 80;
    server_name aluka.ru www.aluka.ru;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name aluka.ru www.aluka.ru;

    ssl_certificate     /etc/letsencrypt/live/aluka.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aluka.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}