server {
    listen 80;
    server_name aluka.ru;  # замените на ваш домен, если есть

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}