server {
    listen 80;
    server_name aluka.ru www.aluka.ru;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}